[client]
showErrorDetails = true

[logger]
level = "error"

[server]
port = 8502
enableXsrfProtection = true
headless = false
runOnSave = true
fileWatcherType = "auto"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

